### ISSUE TITLE
🧊[To-do] Game Functions (Pre-Alpha 1.0)

### ISSUE THREAD

**Issue by MrScautHD** [MrScautHD/Stellution#2]
DEV
===
- [x] Engine [(Easel)](https://github.com/piegfx/Easel)
- [x] Add Registry System
- [x] Add Network System [(Riptide)](https://riptide.tomweiland.net/manual/overview/about-riptide.html)
- [x] Add FixedUpdate https://github.com/piegfx/Easel/issues/5
- [x] Add Overlay System https://github.com/MrScautHD/Stellution/issues/8
- [x] Lazy Register System
- [ ] Add Particle System
- [ ] Add Voice Chat
- [ ] Add Main menu
- [ ] Add Map editor https://github.com/MrScautHD/Stellution/issues/7
- [ ] Add Water system
- [ ] Add Hover physic
- [ ] Add Player movement
- [ ] Add First person and third person
- [x] Wait on Blockbench to add Rig Support https://github.com/JannisX11/blockbench/issues/1679
- [ ] Add Rig and Animations https://github.com/piegfx/Easel/issues/9
- [ ] Add Graphic Settings (Like MSAA...) https://github.com/piegfx/Easel/tree/renderer-rewrite
- [ ] Add Loading Screen https://github.com/piegfx/Easel/issues/15
- [ ] Play Game Trailer by the first time your start https://github.com/piegfx/Easel/issues/18

Player Animations
============
- [ ] Dead Animation
- [x] Run Animation
- [x] Walk Animation
- [x] Idle Animation
- [ ] Jump Animation
- [ ] Weapon Shot Animation
- [ ] Wave Animation
- [ ] Sneak Animation
- [ ] Crawl animation

UI Elements
========
- [x] Add LabelElement
- [x] Add ImageElement
- [x] Add ButtonElement
- [ ] Fix Shadow pos of Text is broken!

Overlays
=====
- [x] Crosshair
- [ ] Map Editor
- [x] Debug

Generally
===
- [ ] Create [Doco](https://dotnet.github.io/docfx/index.html)
- [x] Create Website (https://stellution.com/)

Sounds
===
- [ ] Walking sound
- [ ] Run sound
- [ ] Jump sound
- [ ] Miscellaneous

Music
=====
- [x] Main menu
- [ ] Few radio music

Map
===
- [ ] Add city
- [ ] Add ocean
- [ ] Add models for the city (Textuerer and Modeler)

Texturer:
=====
- [ ] Make main menu design
- [ ] Make models for the map

Bugs
===
- [x] Fix Server crash by shadow system
- [x] Fix Server crash by content manager
- [x] Fix Texture Loading
- [x] Fix Physics (Easel Bug)
- [ ] Fix Translucent material does ignore meshes https://github.com/piegfx/Easel/issues/8
- [x] Fix Shadow Mapping cuts light of https://github.com/piegfx/Easel/issues/12
- [x] Fix FontContent does not has acces to set the FontOptions https://github.com/piegfx/Easel/issues/11
- [x] Fix Sever crash because creating Shadow Map on his side https://github.com/piegfx/Easel/issues/10
- [ ] Fix Physic https://github.com/piegfx/Easel/issues/23
- [ ] Fix Rendering Text needs allot of memory https://github.com/piegfx/Easel/issues/25
- [ ] Wait on Easel Headless implimention https://github.com/piegfx/Easel/issues/21
- [x] Fix Logo has a wierd white line
- [x] Fix Overlay Overlapping
- [x] Fix Fps get limited in fullscreen https://github.com/piegfx/Pie/commit/7f3c8946a1a205baaff3243254bd66f574a1c3ff

**Comment by MrScautHD** [comment]
Info:
Animations in work:
![grafik](https://user-images.githubusercontent.com/65916181/232279764-1ca19e7d-9720-4acd-8365-d9b2e07edd8f.png)

**Comment by MrScautHD** [comment]
Improved!
![grafik](https://github.com/MrScautHD/Stellution/assets/65916181/6bd30591-63b5-46b2-b14d-9b2d6d1d358d)
